  workflow "Jenkins single-shot master" {
    on = "push"
    resolves = ["jenkinsfile-runner-prepackaged"]
  }
    
    action "jenkinsfile-runner-prepackaged" {
    uses = "jenkinsci/jenkinsfile-runner-github-actions@v0.2"
    secrets = ["GITHUB_TOKEN"]
  }




